#!/bin/bash -x

mkdir ~/emacs-contrib
cd ~/emacs-contrib


wget http://downloads.sourceforge.net/project/cedet/cedet/1.0pre7/cedet-1.0pre7.tar.gz?use_mirror=hivelocity

exit


wget http://stud4.tuwien.ac.at/~e0225855/ediprolog/ediprolog.el

##

wget -c http://download.savannah.gnu.org/releases-noredirect/color-theme/color-theme-6.6.0.tar.gz
tar xvfz color-theme-6.6.0.tar.gz

wget -c http://projects.haskell.org/haskellmode-emacs/haskell-mode-2.7.0.tar.gz
tar xvfz haskell-mode-2.7.0.tar.gz


wget -c http://bruda.ca/emacs-prolog/prolog.el

##


git clone http://github.com/secelis/hideshow-org.git
git clone http://github.com/jrockway/cperl-mode.git


wget -c http://www.emacswiki.org/emacs/download/pastebin.el



exit

